add = @{"+"}
sub = @{"-"}
mul = @{"*"}
div = @{"/"}
inp = @{"|"}
print = @{"$"}
debugprint = @{"#"}
dup = @{"."}
swp = @{":"}
ovr = @{","}

float = @{ASCII_DIGIT+~"."~ASCII_DIGIT+}
int = @{ASCII_DIGIT+}
char = @{"'"~"\\"*~ANY}
operator = {add|sub|mul|div|inp|print|debugprint|dup|swp|ovr}
keyword = @{ASCII_ALPHA~ASCII_ALPHANUMERIC*}

token = {float|int|char|operator|keyword}

tokens = { (token~SEPARATOR?)* }